### ISSUE TITLE
Add transactions to DB migrations

### ISSUE THREAD

**Issue by dubharmonic** [flexion/fs-intake-module#427]

**Comment by duselmann** [comment]
My first expectation was that we wanted transactions on DML or CRUD actions. I have since learned we wanted to transactions on DDL. This is not possible for Oracle; however, since Postgres is often ahead of the game, I checked. Postgres does allow most DDL within transactions. I am testing this feature with sequelize.js.

**Comment by sfradkin** [comment]
Correct.  The issue we are now running into is that if we have a bunch of DDL in a migration and one of the statements fails, then we're stuck with partial changes applied to the schema.  The most likely cause of this is that we likely needed to write some data conversion statements before running the DDL.

**Comment by duselmann** [comment]
I have added transactions to all DDL migrations and they work. I tested by pg_dump of the original migrations then dropped all tables and reran the migrations with transactions. They were "identical".

**Comment by duselmann** [comment]
Next I tested by causing a failure and ensured that sequelize honored our transaction. Here is how I did that. Starting from an empty db, I added a record to the applicaitonsFiles table.

```
insert into "applicationFiles" (file_id, application_id, created, updated, application_type, s3_filename, original_filename)
values (1,2,now(),now(),
'applicationType--applicationType--applicationType--applicationType--applicationType--applicationType--applicationType--applicationType--applicationType--applicationType--applicationType--applicationType--applicationType--applicationType--applicationType--',
's3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename-s3filename---',
'originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-originalFilename-'
);
```

Then I created a test migration to test a failure. Notice that all inserted strings are 255 in length and that the migration below is attempting to reduce one while increasing another. The result is that the decrease fails because of the full column (no truncation). The migration is rolled back and the table remains as is. The increased column is rolled back.

```
'use strict';

let Promise = require('bluebird');

const TABLE_NAME = 'applicationFiles';

// alter column sizes and types
// remove phone type

let doTransaction = (queryInterface, operations) => {
  return queryInterface.sequelize.transaction( (trx) => {
    return Promise.each(operations, (operation) => {
      if (operation.operation === 'add') {
        return queryInterface.addColumn(TABLE_NAME, operation.field, {type: operation.type}, {transaction: trx});
      } else if (operation.operation === 'remove') {
        return queryInterface.removeColumn(TABLE_NAME, operation.field, {transaction: trx});
      } else if (operation.operation === 'rename') {
        return queryInterface.renameColumn(TABLE_NAME, operation.field, operation.newField, {transaction: trx});
      } else if (operation.operation === 'change') {
        return queryInterface.changeColumn(TABLE_NAME, operation.field, operation.options, {transaction: trx});
      } else if (operation.operation === 'raw') {
        return queryInterface.sequelize.query(operation.query, { type: queryInterface.sequelize.QueryTypes.RAW, transaction: trx });
      }
    });
  });
};

module.exports = {
  up: function(queryInterface, Sequelize) {

    let operations = [
      {
        operation: 'change',
        field: 's3_filename',
        options: { type: Sequelize.STRING(256), allowNull: false }
      },
      {
        operation: 'change',
        field: 'original_filename',
        options: { type: Sequelize.STRING(128), allowNull: false }
      }
    ];

    return doTransaction(queryInterface, operations);
  },
  down: function(queryInterface, Sequelize) {

    let operations = [
      {
        operation: 'change',
        field: 'appl_info_pri_mailing_state',
        options: { type: Sequelize.STRING(255), allowNull: false }
      },
      {
        operation: 'change',
        field: 'original_filename',
        options: { type: Sequelize.STRING(256), allowNull: false }
      }
    ];

    return doTransaction(queryInterface, operations);
  }
};
```

Here is the description of the table before and after the failed migration. No column have changed.

```
postgres=# \d+ "applicationFiles"
                                                               Table "public.applicationFiles"
      Column       |           Type           |                              Modifiers                               | Storage  | Stats target | Description 
-------------------+--------------------------+----------------------------------------------------------------------+----------+--------------+-------------
 file_id           | integer                  | not null default nextval('"applicationFiles_file_id_seq"'::regclass) | plain    |              | 
 application_id    | integer                  | not null                                                             | plain    |              | 
 application_type  | character varying(255)   | not null                                                             | extended |              | 
 s3_filename       | character varying(255)   | not null                                                             | extended |              | 
 original_filename | character varying(255)   | not null                                                             | extended |              | 
 created           | timestamp with time zone | not null                                                             | plain    |              | 
 updated           | timestamp with time zone | not null                                                             | plain    |              | 
Indexes:
    "applicationFiles_pkey" PRIMARY KEY, btree (file_id)

postgres=# \d+ "applicationFiles"
                                                               Table "public.applicationFiles"
      Column       |           Type           |                              Modifiers                               | Storage  | Stats target | Description 
-------------------+--------------------------+----------------------------------------------------------------------+----------+--------------+-------------
 file_id           | integer                  | not null default nextval('"applicationFiles_file_id_seq"'::regclass) | plain    |              | 
 application_id    | integer                  | not null                                                             | plain    |              | 
 application_type  | character varying(255)   | not null                                                             | extended |              | 
 s3_filename       | character varying(255)   | not null                                                             | extended |              | 
 original_filename | character varying(255)   | not null                                                             | extended |              | 
 created           | timestamp with time zone | not null                                                             | plain    |              | 
 updated           | timestamp with time zone | not null                                                             | plain    |              | 
Indexes:
    "applicationFiles_pkey" PRIMARY KEY, btree (file_id)
```

Here is the sequelize migration run with rollback notification.

```
Daves-MacBook:server daviduselmann$ sequelize db:migrate

Sequelize [Node: 8.0.0, CLI: 2.7.0, ORM: 3.30.4]

Loaded configuration file ".sequelize.js".
Executing (default): SELECT 1+1 AS result
Executing (default): SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';
Executing (default): SELECT tc.constraint_type as "Constraint", c.column_name as "Field", c.column_default as "Default", c.is_nullable as "Null", CASE WHEN c.udt_name = 'hstore' THEN c.udt_name ELSE c.data_type END as "Type", (SELECT array_agg(e.enumlabel) FROM pg_catalog.pg_type t JOIN pg_catalog.pg_enum e ON t.oid=e.enumtypid WHERE t.typname=c.udt_name) AS "special" FROM information_schema.columns c LEFT JOIN information_schema.key_column_usage cu ON c.table_name = cu.table_name AND cu.column_name = c.column_name LEFT JOIN information_schema.table_constraints tc ON c.table_name = tc.table_name AND cu.column_name = c.column_name AND tc.constraint_type = 'PRIMARY KEY'  WHERE c.table_name = 'SequelizeMeta' AND c.table_schema = 'public'
Executing (default): CREATE TABLE IF NOT EXISTS "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , UNIQUE ("name"), PRIMARY KEY ("name"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): SELECT "name" FROM "SequelizeMeta" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
Executing (default): CREATE TABLE IF NOT EXISTS "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , UNIQUE ("name"), PRIMARY KEY ("name"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): SELECT "name" FROM "SequelizeMeta" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
Executing (default): CREATE TABLE IF NOT EXISTS "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , UNIQUE ("name"), PRIMARY KEY ("name"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): SELECT "name" FROM "SequelizeMeta" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
== 11-testChanges: migrating =======
Executing (196ec51b-09b1-4bbd-93ab-d1993c0665f2): START TRANSACTION;
Executing (196ec51b-09b1-4bbd-93ab-d1993c0665f2): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (196ec51b-09b1-4bbd-93ab-d1993c0665f2): ALTER TABLE "applicationFiles" ALTER COLUMN "s3_filename" SET NOT NULL;ALTER TABLE "applicationFiles" ALTER COLUMN "s3_filename" DROP DEFAULT;ALTER TABLE "applicationFiles" ALTER COLUMN "s3_filename" TYPE VARCHAR(256);
Executing (196ec51b-09b1-4bbd-93ab-d1993c0665f2): ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" SET NOT NULL;ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" DROP DEFAULT;ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" TYPE VARCHAR(128);
Executing (196ec51b-09b1-4bbd-93ab-d1993c0665f2): ROLLBACK;
{ SequelizeBaseError: value too long for type character varying(128)
    at Query.formatError (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:115:13)
    at Query.emit (events.js:210:7)
    at Query.handleError (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/pg/lib/query.js:143:8)
    at Client.<anonymous> (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/pg/lib/client.js:186:26)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at TLSSocket.<anonymous> (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/pg/lib/connection.js:133:12)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at TLSSocket.Readable.push (_stream_readable.js:195:10)
    at TLSWrap.onread (net.js:586:20)
  name: 'SequelizeDatabaseError',
  message: 'value too long for type character varying(128)',
  parent: 
   { error: value too long for type character varying(128)
       at Connection.parseE (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/pg/lib/connection.js:567:11)
       at Connection.parseMessage (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/pg/lib/connection.js:391:17)
       at TLSSocket.<anonymous> (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/pg/lib/connection.js:129:22)
       at emitOne (events.js:115:13)
       at TLSSocket.emit (events.js:210:7)
       at addChunk (_stream_readable.js:250:12)
       at readableAddChunk (_stream_readable.js:237:11)
       at TLSSocket.Readable.push (_stream_readable.js:195:10)
       at TLSWrap.onread (net.js:586:20)
     name: 'error',
     length: 99,
     severity: 'ERROR',
     code: '22001',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'varchar.c',
     line: '624',
     routine: 'varchar',
     sql: 'ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" SET NOT NULL;ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" DROP DEFAULT;ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" TYPE VARCHAR(128);' },
  original: 
   { error: value too long for type character varying(128)
       at Connection.parseE (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/pg/lib/connection.js:567:11)
       at Connection.parseMessage (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/pg/lib/connection.js:391:17)
       at TLSSocket.<anonymous> (/Users/daviduselmann/projects/flexion/forest/fs-intake/server/node_modules/pg/lib/connection.js:129:22)
       at emitOne (events.js:115:13)
       at TLSSocket.emit (events.js:210:7)
       at addChunk (_stream_readable.js:250:12)
       at readableAddChunk (_stream_readable.js:237:11)
       at TLSSocket.Readable.push (_stream_readable.js:195:10)
       at TLSWrap.onread (net.js:586:20)
     name: 'error',
     length: 99,
     severity: 'ERROR',
     code: '22001',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'varchar.c',
     line: '624',
     routine: 'varchar',
     sql: 'ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" SET NOT NULL;ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" DROP DEFAULT;ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" TYPE VARCHAR(128);' },
  sql: 'ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" SET NOT NULL;ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" DROP DEFAULT;ALTER TABLE "applicationFiles" ALTER COLUMN "original_filename" TYPE VARCHAR(128);' }
```

Finally, the 11-testChanges.js is NOT in the list.

```
postgres=# select * from "SequelizeMeta";
           name            
---------------------------
 01-noncommapplications.js
 02-addStatus.js
 03-modifyName.js
 04-addSigReason.js
 05-removeTimeFields.js
 06-addControlNum.js
 07-nonCommFieldCleanup.js
 08-applicationfiles.js
 09-noncommChanges.js
 10-tempOutfitter.js
(10 rows)
```
